### ISSUE TITLE
chart data updator bug

### ISSUE THREAD

**Issue by SamiSammour** [aomran/ember-cli-chart#34] opened 2015-08-16 21:28 UTC
Hi there,
there is a problem when updating the chart when the new data length is less than the previous one.
for example if you have the dataset.data.length = 10 then the new dataset.data.length = 3 the chart first 3 points is updated but the rest are still drawn.

**Comment by sbatson5** [comment] 2015-09-30 17:45
I experience this issue with line charts as well.  For example:

<img width="762" alt="screen shot 2015-09-30 at 1 41 25 pm" src="https://cloud.githubusercontent.com/assets/881981/10201243/fdb4a0ae-6778-11e5-8bf6-804dbe32568f.png">

Then updating the number of years we chart:

<img width="601" alt="screen shot 2015-09-30 at 1 42 10 pm" src="https://cloud.githubusercontent.com/assets/881981/10201260/135a5d36-6779-11e5-97a6-102e8b594669.png">

So my array of datapoints has changed length and I would want the whole chart to redraw.  However, there may be use cases where you want to only update the first few data points.  Would it make sense to add a property that forces redraw?

`{{ember-chart type="Line" data=chartData options=chartOptions forceRedraw=true width=500 height=300}}`

Or something to that effect?

**Comment by sbatson5** [comment] 2015-09-30 18:58
@aomran I wrote another PR which should address this.  The issue is that if the number of points for an item changes, the chart won't redraw since we are still charting the same number of datasets.  PR with unit test is here:
https://github.com/aomran/ember-cli-chart/pull/37

**Comment by aomran** [comment] 2016-03-12 15:40
pull request #37 was merged -- that might address this

**Comment by aomran** [comment] 2016-05-08 03:31
Closing this issue since it's been a while and the next major version is being worked on here: https://github.com/aomran/ember-cli-chart/pull/54.

**Closed by aomran** 2016-05-08 03:31 UTC
